### ISSUE TITLE
posix-api-0.4?

### ISSUE THREAD

**Issue by nomeata** [andrewthad/ping#10]
Hi Andrew,

I see you uploaded posix-api-0.4. Will you follow up with an upload of ping? Or is ping not (that) actively maintained?

(I’m tempted to add a network status gadget to my taffybar, and the `ping` library seems like an obvious tool for that, but it’s currently broken on nixpkg unfortunately.)

**Comment by andrewthad** [comment]
Thanks for the nudge. I haven't used this library in a while, but I didn't realize anyone else did either. I've just released ping-0.1.0.4, which should fix the problem you're having once it makes it onto nixpkgs.

**Comment by nomeata** [comment]
> I didn't realize anyone else did either

I’m not using it (yet), merely considering it :-D

Thanks!

**Comment by andrewthad** [comment]
I’ll go ahead and mark this as closed since the version from hackage should work now, but reopen if you run into other issues.
