### ISSUE TITLE
1.0.4 misses CHANGELOG entry

### ISSUE THREAD

**Issue by andreasabel** [andrewthad/ping#11]
https://github.com/andrewthad/ping/blob/2e684608a35a57e8569b0ceb74f80af91b2354ac/CHANGELOG.md?plain=1#L4
Quoted guide says:
> There should be an entry for every single version. 

;-)

**Comment by andrewthad** [comment]
Thanks. Resolved by d3fde7ce204256903008d767466f3cdec0716b38.
