### ISSUE TITLE
Interpreting results question

### ISSUE THREAD

**Issue by sorki** [andrewthad/ping#6]
First of all, thanks for writing this package, it's quite useful!

I'm having some troubles interpreting the ping times when trying to compare this to unix ping.

When I'm trying to ping the gateway I'm getting
``(18718812 ns ,18.718812 ms) -- snd is ns / 10e6``
while unix ping reports ``~0.18 ms``

I'm wondering how it computes this and why there's such a big different. Looking at https://github.com/sparrc/go-ping/blob/master/ping.go it seems to extract RTT from the packet using `bytesToTime` function. Is this also the approach used by unix ping?

**Comment by andrewthad** [comment]
Just to be clear, are you sure that you opened this issue on the right repository? You’ve linked to the source code for a golang implementation of ping  in a different repository.

**Comment by sorki** [comment]
Yes, I'm experimenting with your ping but trying to find out what other implementations are doing time-measurement wise. My ICMP knowledge is pretty limited though.

**Comment by andrewthad** [comment]
Without seeing the code that gave you these results, it's hard to say whether or not something is wrong. But, this has motivated me to introduce something I've been meaning to for a while. If you pull the most recent code on the master branch, you can do this:

    $ git clone https://github.com/andrewthad/ping
    $ cd ping
    $ cabal new-build -f+application
    # This path varies depending on your version of GHC and your architecture
    $ ./dist-newstyle/path/to/executable/multiping host 10.10.10.1
    2569213
    $ ./dist-newstyle/path/to/executable/multiping multihosts -r 3 -d 1 127.0.0.1 10.10.10.1
    10.10.10.1: 1114050 1624842 2341576
    127.0.0.1: 286113 169802 173866
    $ ./dist-newstyle/path/to/executable/multiping --help
    Usage: multiping COMMAND
    
    Available options:
      -h,--help                Show this help text
    
    Available commands:
      host                     One ICMP echo request to a single host
      hosts                    One ICMP echo request to each argument host
      range                    One ICMP echo request to each host in range
      multihosts               Multiple ICMP echo requests to each argument host
      multirange               Multiple ICMP echo requests to each host in range

Ping latencies are printed out as nanoseconds, but all arguments are passed in as seconds. If you use this executable (you probably want the `host` subcommand) and compare it against `ping` and paste the invocations and the output of both commands, that will give me a more clear picture of what's happening.

**Comment by sorki** [comment]
I wrote this test program to be able to compare to unix ping, hence the 10e6 division which should yield milliseconds but results seems to be differ.

```haskell
import qualified Data.Set.Unboxed as SU
import Net.IPv4 hiding (print)
import Network.Icmp.Ping

import Control.Concurrent
import Control.Monad

-- host or ip/ipv6
hostList = [
    ipv4 1 1 1 1
  ]

myAddr :: IPv4
myAddr = ipv4 172 17 1 1

myAddr2 :: IPv4
myAddr2 = ipv4 127 0 0 2

myRange :: IPv4Range
myRange = fromBounds (fromOctets 172 17 1 0) (fromOctets 172 17 1 255)

freq = 1

main = forever $ do
  -- all time return values are in *nano*seconds

  h <- host 1000000 -- wait microseconds
    --(ipv4 8 8 8 8)
    (ipv4 1 1 1 1)
    --myAddr

  case h of
    Left err -> error $ show err
    Right res -> case res of
      Nothing -> print '*'
      Just n -> print (n, fromIntegral n / 1e6)

  mh <- multihosts
    1000000 -- wait for response (microseconds)
    100     -- pause between pings (microseconds)
    20      -- number of pings
    3       -- cutoff
    (SU.fromList hostList)

  print mh
```

**Comment by sorki** [comment]
Now when I look at it I've realized that my last comparison attempt was against different IPs, will retest.

**Comment by andrewthad** [comment]
Could you include either the output of running your program (changing it to target the gateway instead of `1.1.1.1`) or the output of running these commands:

```
multiping host GATEWAY
# The second command will take around 20 seconds
multiping multihosts -r20 -d1 GATEWAY
```

And also include the output of running `ping GATEWAY`.

**Comment by sorki** [comment]
```
$ multiping host 172.17.1.1
354726

$ multiping multihosts -r20 -d1 172.17.1.1
172.17.1.1: 344153 350435 366895 336869 439066 378268 304173 305165 370081 380132 322930 307322 346147 349460 364167 336082 236470 335194 316465 304927
```

ping for reference
```
--- 172.17.1.1 ping statistics ---
651 packets transmitted, 651 received, 0% packet loss, time 665611ms
rtt min/avg/max/mdev = 0.115/0.188/0.348/0.022 ms
```

This looks just a bit (~0.1-0.2ms) offset from unix ping, yesterday I've made the mistake of pinging 1.1.1.1 vs gateway and results were off ~10x.

**Comment by andrewthad** [comment]
Thanks for putting up the output. On low-latency (sub-millisecond) links, I am also able to observe this difference. Notably, pinging localhost gives me different results:

```
$ ping 127.0.0.1
...
rtt min/avg/max/mdev = 0.043/0.046/0.049/0.002 ms
$ multiping multihosts -d1 -r10 127.0.0.1
127.0.0.1: 357232 222753 226879 235718 204510 238666 223822 226346 226183 229867
```

Oddly, I'm seeing the opposite of what you're seeing: `multiping` shows lower latency than `ping` does.

To calculate latency, I use `GHC.Clock.getMonotonicTimeNSec` to get the monotonic system clock right before the `sendto` syscall. I don't put the monotonic clock value in the payload (I just keep it in memory), although that shouldn't have any impact on the correctness of the algorithm. I another system clock call once we get an ICMP repsonse. I don't know how the `ping` that ships with linux is implemented. It might do something a little different, although I don't know how much flexibility there is in the design space for sending a single ICMP request.

I'm not terribly worried about a 0.1-0.2ms difference in latencies reported by different tools. There probably is some explanation of what's going on, but I lack the both the will and the skill set to figure it out.

**Comment by sorki** [comment]
Thank you, I've tried to figure out where the (indeed small) difference is coming from but gave up after a while. Comparing different implementations of userspace ping they seem to measure RTT in similar manner.
