### ISSUE TITLE
Curious 1 bit error in Hosts.hs

### ISSUE THREAD

**Issue by pdobsan** [andrewthad/ping#9]
I recently wanted to install the `ping` package from hackage and the `cabal install` process ended up with the error message:

    src/Network/Icmp/Ping/Hosts.hs:123:48: error:
        Not in scope: ‘SCK.internet’

I supposed that should be SCK.Internet and indeed cloning from the github repo it built with no problem. Fore some reason the source on hackage contains this case error up to the index-state 2022-06-10T15:56:40Z

**Comment by andrewthad** [comment]
try using both `ping` and `posix-api` from GitHub. that should work.

**Comment by pdobsan** [comment]
On Sat, Jun 11, 2022 at 08:09:38AM -0700, Andrew Martin wrote:
> try using both `ping` and `posix-api` from GitHub. that should work.

Yes, that works fine. Thank you!

**Comment by andrewthad** [comment]
In the hackage release of ping-0.1.0.4, this has been resolved. Closing.
